### ISSUE TITLE
`load` not available in top scope as specified in docs

### ISSUE THREAD

**Issue by natnat-mc** [daelvn/alfons#5]
Fixing this issue is also about deciding whether we want it like this (putting `load` in an `always` task) or we want `load` to work in the top scope.

**Comment by daelvn** [comment]
After implementing the new system for #8, I determined that the Taskfile has to be run before `load` can be added to the Taskfile environment. This means that it can only be run inside a function. The proper place to put it would be the `always` task. So, this becomes a documentation issue rather than a code issue.
