### ISSUE TITLE
`load` can override local tasks

### ISSUE THREAD

**Issue by natnat-mc** [daelvn/alfons#8]
Taskfiles loaded with `load` currently overwrite all tasks they define, including tasks that are already defined in another taskfile (including the main one). This can lead to broken parent taskfiles (the `teardown` task can get overwritten, and other tasks can be overwritten by an unrelated task).

Multiple solutions are possible:
1. keep the current behavior
	-> leads to hard-to-debug cases when tasks get seemingly never executed and unrelated asks get executed seemingly at random
2. silently drop `load`ed tasks
	-> leads to hard-to-debug cases, but tasks from the parent get executed instead of the child
3. throw an error if any duplicate task is loaded (except potentially `always` which would be run immediately and `teardown` which would get added to a queue)
	-> leads to a problem where taskfiles are not independent and `load`ing two taskfiles that work fine on their own could fail
4. namespace taskfiles: `load 'fetch'` would load `fetch`'s tasks in `tasks.fetch` that would be a table
	-> breaking change: tasks are no longer `load`ed as they do in 4.1.4 and are now a deep table
	- how does the taskfile itself see its tasks?
		- if it also sees them namespaced then it is no longer working like it would if it was a main taskfile
		- if it doesn't then the environment needs to be per-taskfile and not global, which is a major rewrite
5. mix 2 and 4
	- load each taskfile in its own environment
		-> cache loaded taskfiles or load them again each time ?
	- immediately run `always` and queue `teardown`
		-> run them once or for each `load` call ?
	- export its tasks to its parent taskfile if it isn't already defined (recursively)
	-> this would avoid a breaking change, but would also require a major rewrite of the environment and loading systems

**Comment by daelvn** [comment]
thank you for unearthing this pile of issues out of a single minor inconvenience

**Comment by natnat-mc** [comment]
discussion on the MoonScript discord here for more details:
https://discordapp.com/channels/454435414044966913/454435414497820673/758811988468957204

**Comment by daelvn** [comment]
Posting this proposal that @natnat-mc suggested, although it needs further explanation. This will probably get discussed in the discord first.

> okay so i have an idea about the namespace thing:
> - the environment contains just the `tasks` table for each > taskfile
> - it also has an `__index` to the global environment (and probably `__newindex` if there's a reason to that to be there)
> - when you `load` a taskfile, it gets its own environment with its own `tasks` table
> - every task in its environment that isn't already somewhere in its parents environment also gets copied there, potentially recursively
> - its `always` task is called
> - its `teardown` task is added to the queue

**Comment by daelvn** [comment]
This comment will explain the solution I am currently implementing, which I guess could be categorized as number 5.

- Each Taskfile is now loaded with its own environment, with the default environment and functions in `provide` being accessed through an `__index` metamethod instead of having to make clones of the environment every time.
- There is a global environment table, not accessible to the user, which contains all the environments for all the loaded Taskfiles. `env.tasks` uses this internally to lookup tasks. Tasks defined in the caller taskfile always take precedence.
- The last point implies correctly that all tasks are available to each other, no matter where they are defined, as long as they have been defined at some point. Interestingly, it even deals with cyclical dependencies thanks to this global environment, not resulting in a loop that goes on "forever".
- The `always` task is called once for each taskfile loaded. The `teardown` task will be queued in reverse order of loading. It is still unclear whether the teardown tasks will be run manually, using a trigger function such as `env.teardown!`, or in any other manner. The logical thing would be to include `default` tasks in the teardown trigger (possibly find another name, like `env.finalize!`), checking the number of tasks that have been run and running the default tasks accordingly. Each taskfile should keep its own number of run tasks.
- `__newindex` on the `env` table replaces the old mechanism for adding tasks via global/export-syntax. We used to have to iterate through the environment, checking for functions whose name was not included in the original table. Now this can simply be a trigger and reduce time.

More implementation details upcoming, hopefully. Docs should be updated accordingly.

**Comment by daelvn** [comment]
Reminders for self:

- [x] Test that global/export syntax works properly.
- [x] ~~Implement teardown queue.~~
- [x] Implement finalize trigger. (? - See above)
- [x] Go to sleep at a decent time. I swear it's just for 4.2.

**Comment by daelvn** [comment]
Just had a realization moment, reading the code for the CLI tool... `teardown` is supposed to run after every called task, not after the file is done. This changes so many things... I wrote this thing.... How could I just forget that it worked like that,,.,.

As such, I will look into implementing a `finalize` task that does what I thought `teardown` was doing all this time: running when Alfons exits. Replace all past mentions of the teardown queue with the finalize queue, I guess?
